## OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 222de8a09d7ca4609f11
            client-secret: 8f8fe93178142e15900d5864128557e99cef791c
          google:
            client-id: 222de8a09d7ca4609f11
            client-secret: 8f8fe93178142e15900d5864128557e99cef791c

## H2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

## JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true   //운영할 때는 system.out로 sql를 보여주기때문에 쓰지 말아야한다
        format_sql: true  //sql 이쁘게 보이게
        default_batch_fetch_size: 100